# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Licenta_Design/Licenta_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design || ORIG_REF_NAME==Licenta_Design} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_processing_system7_0_0/Licenta_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_processing_system7_0_0 || ORIG_REF_NAME==Licenta_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_bram_ctrl_0_0/Licenta_Design_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Licenta_Design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_proc_sys_reset_0_0/Licenta_Design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_proc_sys_reset_0_0 || ORIG_REF_NAME==Licenta_Design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_xbar_0/Licenta_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_xbar_0 || ORIG_REF_NAME==Licenta_Design_xbar_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_interconnect_0_0/Licenta_Design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_interconnect_0_0 || ORIG_REF_NAME==Licenta_Design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_timer_0_0/Licenta_Design_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_timer_0_0 || ORIG_REF_NAME==Licenta_Design_axi_timer_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_timebase_wdt_0_0/Licenta_Design_axi_timebase_wdt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_timebase_wdt_0_0 || ORIG_REF_NAME==Licenta_Design_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_gpio_0_0/Licenta_Design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_gpio_0_0 || ORIG_REF_NAME==Licenta_Design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_dma_0_0/Licenta_Design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_dma_0_0 || ORIG_REF_NAME==Licenta_Design_axi_dma_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_blk_mem_gen_0_0/Licenta_Design_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_blk_mem_gen_0_0 || ORIG_REF_NAME==Licenta_Design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_traffic_gen_0_0/Licenta_Design_axi_traffic_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_traffic_gen_0_0 || ORIG_REF_NAME==Licenta_Design_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_smartconnect_0_0/Licenta_Design_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_smartconnect_0_0 || ORIG_REF_NAME==Licenta_Design_smartconnect_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_axi_fifo_mm_s_0_0/Licenta_Design_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==Licenta_Design_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_5/Licenta_Design_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_5 || ORIG_REF_NAME==Licenta_Design_auto_pc_5} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_0/Licenta_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_0 || ORIG_REF_NAME==Licenta_Design_auto_pc_0} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_1/Licenta_Design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_1 || ORIG_REF_NAME==Licenta_Design_auto_pc_1} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_2/Licenta_Design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_2 || ORIG_REF_NAME==Licenta_Design_auto_pc_2} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_3/Licenta_Design_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_3 || ORIG_REF_NAME==Licenta_Design_auto_pc_3} -quiet] -quiet

# IP: bd/Licenta_Design/ip/Licenta_Design_auto_pc_4/Licenta_Design_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Licenta_Design_auto_pc_4 || ORIG_REF_NAME==Licenta_Design_auto_pc_4} -quiet] -quiet

# XDC: c:/Users/patri/Desktop/Licenta_1/Licenta_1.gen/sources_1/bd/Licenta_Design/Licenta_Design_ooc.xdc
